# Notebook 02 - Preprocesamiento

## Objetivo
Aplicar limpieza de texto paso a paso, mostrando el antes y despues de cada transformacion sin combinar todos los pasos de una sola vez.

In [1]:
import re
import pandas as pd
from IPython.display import display

ruta = "../datasets/frases.csv"
df_base = pd.read_csv(ruta)

# Creamos un dataset pequeno con ruido para practicar limpieza paso a paso
df = df_base.head(10).copy()
df["texto_original"] = [
    f"{txt} !!! {2020 + i}  " if i % 2 == 0 else f"{txt} ???   {300 + i}"
    for i, txt in enumerate(df["frase"])
]
df = df[["texto_original"]]
display(df.head())

                                      texto_original
0  Hoy estudiaremos procesamiento de lenguaje nat...
1  El modelo aprende patrones en los datos ???   301
2  Me gusta aprender inteligencia artificial !!! ...
3  TensorFlow facilita la construccion de redes n...
4  Los embeddings representan palabras como vecto...

## 1) Convertir a minusculas
Reducimos variaciones artificiales entre palabras como `NLP` y `nlp`.

In [2]:
df["paso_1_minusculas"] = df["texto_original"].str.lower()
display(df[["texto_original", "paso_1_minusculas"]].head())

,texto_original,paso_1_minusculas
0,Hoy estudiaremos procesamiento de lenguaje nat...,hoy estudiaremos procesamiento de lenguaje nat...
1,El modelo aprende patrones en los datos ??? 301,el modelo aprende patrones en los datos ??? 301
2,Me gusta aprender inteligencia artificial !!! ...,me gusta aprender inteligencia artificial !!! ...
3,TensorFlow facilita la construccion de redes n...,tensorflow facilita la construccion de redes n...
4,Los embeddings representan palabras como vecto...,los embeddings representan palabras como vecto...

## 2) Eliminar signos de puntuacion y simbolos
Usamos expresiones regulares para conservar letras, numeros y espacios.

In [3]:
df["paso_2_sin_signos"] = df["paso_1_minusculas"].str.replace(r"[^\w\s]", " ", regex=True)
display(df[["paso_1_minusculas", "paso_2_sin_signos"]].head())

,paso_1_minusculas,paso_2_sin_signos
0,hoy estudiaremos procesamiento de lenguaje nat...,hoy estudiaremos procesamiento de lenguaje nat...
1,el modelo aprende patrones en los datos ??? 301,el modelo aprende patrones en los datos 301
2,me gusta aprender inteligencia artificial !!! ...,me gusta aprender inteligencia artificial ...
3,tensorflow facilita la construccion de redes n...,tensorflow facilita la construccion de redes n...
4,los embeddings representan palabras como vecto...,los embeddings representan palabras como vecto...

## 3) Eliminar numeros
Este paso depende del problema. En este ejemplo lo aplicamos para concentrarnos en vocabulario textual.

In [4]:
df["paso_3_sin_numeros"] = df["paso_2_sin_signos"].str.replace(r"\d+", " ", regex=True)
display(df[["paso_2_sin_signos", "paso_3_sin_numeros"]].head())

,paso_2_sin_signos,paso_3_sin_numeros
0,hoy estudiaremos procesamiento de lenguaje nat...,hoy estudiaremos procesamiento de lenguaje nat...
1,el modelo aprende patrones en los datos 301,el modelo aprende patrones en los datos
2,me gusta aprender inteligencia artificial ...,me gusta aprender inteligencia artificial
3,tensorflow facilita la construccion de redes n...,tensorflow facilita la construccion de redes n...
4,los embeddings representan palabras como vecto...,los embeddings representan palabras como vecto...

## 4) Eliminar espacios duplicados
Despues de quitar signos y numeros suelen quedar multiples espacios.

In [5]:
df["paso_4_espacios"] = (
    df["paso_3_sin_numeros"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)
display(df[["paso_3_sin_numeros", "paso_4_espacios"]].head())

,paso_3_sin_numeros,paso_4_espacios
0,hoy estudiaremos procesamiento de lenguaje nat...,hoy estudiaremos procesamiento de lenguaje nat...
1,el modelo aprende patrones en los datos,el modelo aprende patrones en los datos
2,me gusta aprender inteligencia artificial,me gusta aprender inteligencia artificial
3,tensorflow facilita la construccion de redes n...,tensorflow facilita la construccion de redes n...
4,los embeddings representan palabras como vecto...,los embeddings representan palabras como vectores

## Resultado final y comparacion
Observa el antes y despues completo para cada texto.

In [6]:
display(df[["texto_original", "paso_4_espacios"]])

print("Total de filas procesadas:", len(df))

,texto_original,paso_4_espacios
0,Hoy estudiaremos procesamiento de lenguaje nat...,hoy estudiaremos procesamiento de lenguaje nat...
1,El modelo aprende patrones en los datos ??? 301,el modelo aprende patrones en los datos
2,Me gusta aprender inteligencia artificial !!! ...,me gusta aprender inteligencia artificial
3,TensorFlow facilita la construccion de redes n...,tensorflow facilita la construccion de redes n...
4,Los embeddings representan palabras como vecto...,los embeddings representan palabras como vectores
5,Cada token tiene un indice numerico ??? 305,cada token tiene un indice numerico
6,El padding iguala la longitud de las secuencia...,el padding iguala la longitud de las secuencias
7,La limpieza del texto reduce ruido ??? 307,la limpieza del texto reduce ruido
8,Las reseñas pueden expresar sentimientos !!! 2...,las reseñas pueden expresar sentimientos
9,Este curso combina teoria y practica ??? 309,este curso combina teoria y practica

Total de filas procesadas: 10

## Preguntas de reflexion
1. Que problemas podrian surgir si eliminas numeros en todos los casos?
2. En que tipo de dominio no conviene eliminar signos de puntuacion?
3. Que paso de limpieza te parece mas sensible para perder informacion?