# Notebook 05 - GPT y Generacion de Texto

## Objetivos
- Generar texto con GPT-2.
- Comparar temperatura, top_p y top_k.
- Aplicar prompts de resumen y reescritura.

## Introduccion
GPT es decoder-only y autoregresivo: predice el siguiente token. Los parametros de muestreo controlan creatividad vs coherencia.

In [1]:
from transformers import pipeline, set_seed
from IPython.display import display
import pandas as pd

set_seed(42)
generator = pipeline('text-generation', model='gpt2')
print('GPT-2 listo para generar texto')

c:\Users\juand\anaconda3\envs\tf_windows\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\juand\anaconda3\envs\tf_windows\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\juand\.cache\huggingface\hub\models--gpt2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Device set to use cpu

GPT-2 listo para generar texto

## 1) Generacion basica

In [2]:
prompt = 'In machine learning, transformers'
salida = generator(prompt, max_new_tokens=40, do_sample=False)
print(salida[0]['generated_text'])

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

In machine learning, transformers are used to transform data into a series of data structures. The data structures are then transformed into a series of data structures.

The data structures are then transformed into a series of data structures.

## 2) Comparacion de temperatura

In [3]:
temperaturas = [0.3, 0.7, 1.2]
filas = []
for temp in temperaturas:
    out = generator(
        'The future of NLP is',
        max_new_tokens=25,
        do_sample=True,
        temperature=temp,
    )
    filas.append({'temperatura': temp, 'texto': out[0]['generated_text']})

display(pd.DataFrame(filas))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

   temperatura                                              texto
0          0.3  The future of NLP is uncertain. The current st...
1          0.7  The future of NLP is uncertain. It could be th...
2          1.2  The future of NLP is bright, this time of year...

## 3) Top-p (nucleus) vs Top-k

In [4]:
base = 'Artificial intelligence can help companies'
configs = [
    {'nombre': 'top_k=10', 'top_k': 10, 'top_p': 1.0},
    {'nombre': 'top_p=0.9', 'top_k': 0, 'top_p': 0.9},
    {'nombre': 'top_p=0.5', 'top_k': 0, 'top_p': 0.5},
]
comparacion = []
for cfg in configs:
    out = generator(
        base,
        max_new_tokens=30,
        do_sample=True,
        temperature=0.8,
        top_k=cfg['top_k'],
        top_p=cfg['top_p'],
    )
    comparacion.append({'config': cfg['nombre'], 'texto': out[0]['generated_text']})

display(pd.DataFrame(comparacion))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

      config                                              texto
0   top_k=10  Artificial intelligence can help companies und...
1  top_p=0.9  Artificial intelligence can help companies to ...
2  top_p=0.5  Artificial intelligence can help companies sol...

## 4) Prompt de resumen

In [5]:
documento = (
    'Transformers replaced recurrent layers with self-attention, '
    'enabling parallel training and better long-range dependencies.'
)
prompt_resumen = f'Summarize in one sentence:\n{documento}\nSummary:'
resumen = generator(prompt_resumen, max_new_tokens=35, temperature=0.5)[0]['generated_text']
print(resumen)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Summarize in one sentence:
Transformers replaced recurrent layers with self-attention, enabling parallel training and better long-range dependencies.
Summary:
I've been working on a very small prototype for a neural net, based on the neural network that I built in my previous post. The goal is to create a full

## 5) Prompt de reescritura

In [6]:
texto_formal = 'The quarterly results exceeded expectations due to strong demand.'
prompt_rewrite = (
    f'Rewrite for a general audience:\n{texto_formal}\nRewritten:'
)
reescrito = generator(prompt_rewrite, max_new_tokens=40, temperature=0.7)[0]['generated_text']
print(reescrito)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Rewrite for a general audience:
The quarterly results exceeded expectations due to strong demand.
Rewritten:
At one point in time, Rewrite for a general audience exceeded expectations due to strong demand. Rewrite for a media and digital audience:
Rewrite for a media and digital audience:

## 6) Ejemplos de prompt engineering

In [7]:
prompts = [
    'List three benefits of transformers in NLP:',
    'Explain self-attention to a beginner:',
    'Complete: Attention is all you need because',
]
for p in prompts:
    txt = generator(p, max_new_tokens=30, temperature=0.6)[0]['generated_text']
    print('-' * 60)
    print(txt)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

------------------------------------------------------------
List three benefits of transformers in NLP:

1. It is possible to read a list with a single transform.

2. It is possible to read a list with multiple transform

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

------------------------------------------------------------
Explain self-attention to a beginner:

"It's the first time I've ever been able to do this. I've been so focused on doing it for so long that I
------------------------------------------------------------
Complete: Attention is all you need because you're in the right place.

Note: The tutorial assumes you have the latest version of the Adobe Flash Player, which you can install from

## Resultados
Generamos texto con distintos parametros y observamos trade-offs entre diversidad, fluidez y repeticion.

## Conclusiones
GPT-2 es pequeno pero ilustra principios de LLMs. Temperatura alta aumenta creatividad; top_p restringe el nucleo probabilistico de tokens candidatos.

## Ejercicios guiados resueltos
**Ejercicio:** Genera tres veces con la misma semilla y compara estabilidad.

**Solucion:**

In [8]:
set_seed(123)
a = generator('Data science', max_new_tokens=15, do_sample=True, temperature=0.7)[0]['generated_text']
set_seed(123)
b = generator('Data science', max_new_tokens=15, do_sample=True, temperature=0.7)[0]['generated_text']
print('Iguales con misma semilla:', a == b)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Iguales con misma semilla: True

## Ejercicios propuestos
1. Diseña un prompt few-shot con 2 ejemplos de tono formal.
2. Mide longitud promedio generada por configuracion.
3. Prueba penalizacion de repeticion (`repetition_penalty`).

## Preguntas de reflexion
1. Cuando conviene `do_sample=False`?
2. Que riesgo tiene temperatura muy alta en produccion?
3. Como evaluarias calidad de un resumen generado?